#' Simulate Exponential Pollution Decay Across Multiple Lakes
#'
#' Simulates pollution concentration trajectories for multiple lakes using
#' an exponential decay ordinary differential equation (ODE). Each lake has
#' its own initial pollution state and decay rate, creating between-lake
#' heterogeneity.
#'
#' The underlying process follows:
#'
#' \deqn{
#' C_j(t) = C_{0,j} \exp(-r_j t)
#' }
#'
#' where \eqn{C_{0,j}} is the initial pollution concentration for lake \eqn{j}
#' and \eqn{r_j} is the lake-specific decay rate.
#'
#' Initial concentration is generated from spill characteristics:
#'
#' \deqn{
#' C_{0,j} =
#' \mu_C + \beta_{spill}S_j + \epsilon_j
#' }
#'
#' and decay rate depends on water flow:
#'
#' \deqn{
#' r_j =
#' \mu_r + \beta_{flow}F_j + \eta_j
#' }
#'
#' where \eqn{S_j} is the initial spill size and \eqn{F_j} is the lake flow
#' characteristic.
#'
#' Observed pollution measurements are generated by adding Gaussian measurement
#' error around the deterministic ODE solution.
#'
#' @param num_lakes Number of simulated lakes.
#' @param num_weeks Number of time points to simulate for each lake.
#' @param mean_polution_concentration Population mean initial pollution concentration.
#' @param mean_rate_decay Population mean pollution decay rate.
#' @param mean_initial_spill_size Mean initial spill size across lakes.
#' @param sd_intial_spill_size Standard deviation of initial spill sizes.
#' @param beta_spill_size Effect of spill size on initial pollution concentration.
#' @param beta_flow_rate Effect of flow rate on pollution decay rate.
#' @param sd_initial_state Standard deviation of lake-specific initial concentration deviations.
#' @param sd_rate_decay Standard deviation of lake-specific decay rate deviations.
#' @param sd_pollution Observation noise standard deviation.
#'
#' @return A data frame containing:
#' \describe{
#'   \item{week}{Time point of measurement.}
#'   \item{lake_id}{Lake identifier.}
#'   \item{flow}{Lake flow covariate.}
#'   \item{initial_spill}{Initial spill size for the lake.}
#'   \item{pollution_concentration}{Simulated observed pollution concentration.}
#'   \item{true_mu}{Underlying ODE trajectory before measurement noise.}
#' }
#'
#' @examples
#' data <- simulate_ode_lake(
#'   num_lakes = 20,
#'   num_weeks = 52
#' )
#'
#' plot(data$week, data$pollution_concentration)
#'
#' @export
simulate_ode_lake <- function(
  num_lakes = 30,
  num_weeks = 52,
  mean_polution_concentration = 10,
  mean_rate_decay = 0.08,
  mean_initial_spill_size = 5,
  sd_intial_spill_size = 2,
  beta_spill_size = 0.8,
  beta_flow_rate = 0.03,
  sd_initial_state = 1,
  sd_rate_decay = 0.015,
  sd_pollution = 0.5
){

  # Time and N observation 
  time <- 1:num_weeks
  n <- num_weeks * num_lakes

  # Create Ids
  ids <- make_nested_ids(levels = list(lake = num_lakes, weeks = num_weeks))

  # Covariates 
  flow <- rnorm(num_lakes, 0, 1)
  initial_spill_size <- rnorm(num_lakes, mean_initial_spill_size, sd_intial_spill_size)

  # Paramters 
  xo <- mean_polution_concentration + beta_spill_size * initial_spill_size + sd_initial_state * rnorm(num_lakes)
  r  <- mean_rate_decay + beta_flow_rate * flow + sd_rate_decay * rnorm(num_lakes)

  # ODE predictor 
  mu <- xo[ids$lake_id] * exp(-r[ids$lake_id] * ids$weeks_id)

  # Sample from normal distribution 
  pollution <- rnorm(n, mean = mu, sd = sd_pollution)

  # Return a dataframe 
  data.frame(
    week = ids$weeks_id,
    lake_id = ids$lake_id,
    flow = flow[ids$lake_id],
    initial_spill = initial_spill_size[ids$lake_id],
    pollution_concentration = pollution
  )
}