#' Simulate Pollution Dynamics Using an Ornstein–Uhlenbeck Process
#'
#' Simulates longitudinal pollution measurements for multiple lakes using a
#' stochastic differential equation (SDE). The latent pollution concentration
#' evolves according to a zero-mean Ornstein–Uhlenbeck process, allowing
#' pollution to decay toward zero while experiencing continuous random
#' environmental fluctuations.
#'
#' The latent process is governed by
#'
#' \deqn{
#' dC_t = -r_j C_t,dt + \sigma_{OU},dW_t
#' }
#'
#' where \eqn{C_t} is the pollution concentration, \eqn{r_j} is the
#' lake-specific decay rate, \eqn{\sigma_{OU}} controls the magnitude of
#' stochastic environmental fluctuations, and \eqn{dW_t} denotes Brownian
#' motion.
#'
#' Rather than numerically approximating the SDE, the simulator uses the
#' analytical transition distribution of the Ornstein–Uhlenbeck process:
#'
#' \deqn{
#' C_{t+\Delta t}
#' \sim
#' N\left(
#' C_t e^{-r_j\Delta t},
#' \frac{\sigma_{OU}^2}{2r_j}
#' \left(1-e^{-2r_j\Delta t}\right)
#' \right)
#' }
#'
#' Initial pollution concentration depends on spill size:
#'
#' \deqn{
#' C_{0,j}
#' =
#' \mu_C
#' +
#' \beta_{spill}S_j
#' +
#' \epsilon_j
#' }
#'
#' while the decay rate depends on lake flow:
#'
#' \deqn{
#' r_j
#' =
#' \exp\left(
#' \mu_r
#' +
#' \beta_{flow}F_j
#' +
#' \eta_j
#' \right)
#' }
#'
#' Finally, observed pollution measurements are generated by adding Gaussian
#' measurement error to the latent process.
#'
#' @param num_lakes Number of lakes.
#' @param num_weeks Number of weekly observations per lake.
#' @param mean_polution_concentration Population mean initial pollution concentration.
#' @param mean_rate_decay Mean log decay rate.
#' @param mean_initial_spill_size Mean spill size.
#' @param sd_intial_spill_size Standard deviation of spill size.
#' @param beta_spill_size Effect of spill size on the initial pollution concentration.
#' @param beta_flow_rate Effect of flow on the decay rate.
#' @param sd_initial_state Standard deviation of lake-specific initial conditions.
#' @param sd_rate_decay Standard deviation of lake-specific decay rates.
#' @param sd_pollution Standard deviation of observation error.
#' @param dt Time step between successive observations.
#' @param ou_sigma Diffusion parameter controlling the magnitude of stochastic process noise.
#'
#' @return A data frame containing one row per lake-week observation.
#' \describe{
#'   \item{week}{Week of observation.}
#'   \item{lake_id}{Lake identifier.}
#'   \item{flow}{Lake flow covariate.}
#'   \item{initial_spill_size}{Initial spill size.}
#'   \item{decay_rate}{Lake-specific exponential decay rate.}
#'   \item{latent_pollution}{True latent pollution concentration generated by the SDE.}
#'   \item{pollution}{Observed pollution concentration after measurement error.}
#' }
#'
#' @details
#' This simulation illustrates a stochastic extension of exponential decay.
#' Unlike deterministic ordinary differential equation models, the
#' Ornstein–Uhlenbeck process allows the latent pollution trajectory to evolve
#' randomly through time while remaining mean-reverting toward zero. The
#' resulting data are suitable for demonstrating Bayesian state-space models,
#' stochastic differential equation inference, Kalman filtering, and latent
#' process modeling.
#'
#' @examples
#' data <- simulate_sde_ou_lake()
#'
#' head(data)
#'
#' @export
simulate_sde_ou_lake <- function(
  num_lakes = 30,
  num_weeks = 52,
  mean_polution_concentration = 10,
  mean_rate_decay = 0.08,
  mean_initial_spill_size = 5,
  sd_intial_spill_size = 2,
  beta_spill_size = 0.8,
  beta_flow_rate = 0.03,
  sd_initial_state = 1,
  sd_rate_decay = 0.015,
  sd_pollution = 0.5,
  dt = 1,
  ou_sigma = 2
){

  ## Number of observations
  n <- num_lakes * num_weeks

  ## Nested IDs
  ids <- make_nested_ids(levels = list(lake = num_lakes,week = num_weeks))

  ## Lake-level covariates
  flow <- rnorm(num_lakes)
  initial_spill_size <- rnorm(num_lakes, mean_initial_spill_size, sd_intial_spill_size)

  ## Lake-specific parameters
  x0 <- mean_polution_concentration + beta_spill_size * initial_spill_size + sd_initial_state * rnorm(num_lakes)
  r <- exp(mean_rate_decay + beta_flow_rate * flow + sd_rate_decay * rnorm(num_lakes))

  ## Latent OU process
  C <- matrix(
    NA_real_,
    nrow = num_weeks,
    ncol = num_lakes
  )
  # Initilize the process 
  C[1, ] <- x0

  # OU Process 
  for(i in 2:num_weeks){
    mean_t <- C[i - 1, ] * exp(-r * dt)
    sd_t   <- sqrt((ou_sigma^2 / (2 * r)) *(1 - exp(-2 * r * dt)))
    C[i, ] <- rnorm(num_lakes, mean = mean_t, sd = sd_t)
  }

  ## Convert to observation-level vectors
  latent_pollution <- as.vector(C)
  pollution <- rnorm(n, mean = latent_pollution, sd = sd_pollution)

  data.frame(
    lake_id = ids$lake_id,
    week    = ids$week_id,
    flow    = flow[ids$lake_id],
    initial_spill_size = initial_spill_size[ids$lake_id],
    pollution          = pollution
  )

}